language: ruby

rvm:
  - 2.2

branches:
  only:
  - master
  - develop
  - setup_travis

before_install:
  # get the repos for bosh-lite and cloud foundery
  - git clone https://github.com/IBM-Bluemix/Kitura-Starter
  - git clone https://github.com/IBM-Bluemix/swift-helloworld.git
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update
  - sudo apt-get install cf-cli
  - cf login -a https://api.ng.bluemix.net -u $BLUEMIX_USER -p $BLUEMIX_PASS -s dev -o $BLUEMIX_USER
  
script:
  - ./ci/performance_validator.sh Kitura-Starter $KITURA_STARTER_TIME $TRAVIS_BRANCH $TIMES_TO_REPEAT_TO_SUCCESS $KITURA_STARTER_REPUSH_TIME
  - rm -rf Kitura-Starter
  - ./ci/performance_validator.sh swift-helloworld $SWIFT_HELLOWORLD_TIME $TRAVIS_BRANCH $TIMES_TO_REPEAT_TO_SUCCESS $SWIFT_HELLOWORLD_REPUSH_TIME
  - rm -rf swift-helloworld

after_success:
  - ./ci/create_git_tag.sh

deploy:
  provider: releases
  user: $GITHUB_USER
  password: $GITHUB_PASS
  file: "$TRAVIS_BUILD_DIR/buildpack_swift_v$VERSION-$DATE.zip"
  skip_cleanup: true
  on:
    repo: IBM-Swift/swift-buildpack
    branch: master
